# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/Takuma-Game-Store
spring.datasource.username=postgres
spring.datasource.password=GGgaming123#$#$
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Optional: Show SQL queries in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

# GOOGLE OAUTH2 LOGINS
spring.security.oauth2.client.registration.google.client-id=657748105326-si8pmfkticiv0gj9m5k0lpodjlpbhjnl.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG

